<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 摄像头部件[包含连杆属性、关节属性] -->
    <xacro:property name="camera_length" value="0.02" />
    <xacro:property name="camera_width" value="0.03" />
    <xacro:property name="camera_height" value="0.03" />
    <xacro:property name="camera_mass" value="0.01" />
    <xacro:property name="x_move" value="0.08" />
    <xacro:property name="y_move" value="0" />    
    <xacro:property name="z_move" value="${(base_length+camera_height)/2}" />

    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="camera_colour">
                <color rgba="0 1 0 0.5"/>
            </material>
        </visual>
        <collision>
           <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <!-- 调用惯性矩阵函数 -->
        <xacro:Box_inertial_matrix m="${camera_mass}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
    </link>
    <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>
    <joint name="base2camera" type="fixed">
            <!-- 父级link -->
            <parent link="base_link"/>
            <!-- 子级link    -->
            <child link="camera"/>
            <!-- 设置偏移量 -->
            <origin xyz="${x_move} ${y_move} ${z_move}" rpy="0 0 0"/>
    </joint>
</robot>