// Generated by gencpp from file server/Addints.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_ADDINTS_H
#define SERVER_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <server/AddintsRequest.h>
#include <server/AddintsResponse.h>


namespace server
{

struct Addints
{

typedef AddintsRequest Request;
typedef AddintsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Addints
} // namespace server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server::Addints > {
  static const char* value()
  {
    return "48d0f254fecb160bea4c43b66d25c762";
  }

  static const char* value(const ::server::Addints&) { return value(); }
};

template<>
struct DataType< ::server::Addints > {
  static const char* value()
  {
    return "server/Addints";
  }

  static const char* value(const ::server::Addints&) { return value(); }
};


// service_traits::MD5Sum< ::server::AddintsRequest> should match
// service_traits::MD5Sum< ::server::Addints >
template<>
struct MD5Sum< ::server::AddintsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server::Addints >::value();
  }
  static const char* value(const ::server::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AddintsRequest> should match
// service_traits::DataType< ::server::Addints >
template<>
struct DataType< ::server::AddintsRequest>
{
  static const char* value()
  {
    return DataType< ::server::Addints >::value();
  }
  static const char* value(const ::server::AddintsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server::AddintsResponse> should match
// service_traits::MD5Sum< ::server::Addints >
template<>
struct MD5Sum< ::server::AddintsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server::Addints >::value();
  }
  static const char* value(const ::server::AddintsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server::AddintsResponse> should match
// service_traits::DataType< ::server::Addints >
template<>
struct DataType< ::server::AddintsResponse>
{
  static const char* value()
  {
    return DataType< ::server::Addints >::value();
  }
  static const char* value(const ::server::AddintsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_MESSAGE_ADDINTS_H
