// Generated by gencpp from file server/AddintsRequest.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_ADDINTSREQUEST_H
#define SERVER_MESSAGE_ADDINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server
{
template <class ContainerAllocator>
struct AddintsRequest_
{
  typedef AddintsRequest_<ContainerAllocator> Type;

  AddintsRequest_()
    : num1(0)
    , num2(0)  {
    }
  AddintsRequest_(const ContainerAllocator& _alloc)
    : num1(0)
    , num2(0)  {
  (void)_alloc;
    }



   typedef int64_t _num1_type;
  _num1_type num1;

   typedef int64_t _num2_type;
  _num2_type num2;





  typedef boost::shared_ptr< ::server::AddintsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::AddintsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddintsRequest_

typedef ::server::AddintsRequest_<std::allocator<void> > AddintsRequest;

typedef boost::shared_ptr< ::server::AddintsRequest > AddintsRequestPtr;
typedef boost::shared_ptr< ::server::AddintsRequest const> AddintsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::AddintsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::AddintsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server::AddintsRequest_<ContainerAllocator1> & lhs, const ::server::AddintsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.num1 == rhs.num1 &&
    lhs.num2 == rhs.num2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server::AddintsRequest_<ContainerAllocator1> & lhs, const ::server::AddintsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server::AddintsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::AddintsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AddintsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AddintsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AddintsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AddintsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::AddintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b7233452eef3749ca025e90606b0956";
  }

  static const char* value(const ::server::AddintsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b7233452eef3749ULL;
  static const uint64_t static_value2 = 0xca025e90606b0956ULL;
};

template<class ContainerAllocator>
struct DataType< ::server::AddintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/AddintsRequest";
  }

  static const char* value(const ::server::AddintsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::AddintsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num1\n"
"int64 num2\n"
;
  }

  static const char* value(const ::server::AddintsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::AddintsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num1);
      stream.next(m.num2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddintsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::AddintsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::AddintsRequest_<ContainerAllocator>& v)
  {
    s << indent << "num1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num1);
    s << indent << "num2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_ADDINTSREQUEST_H
