// Generated by gencpp from file server/AddintsResponse.msg
// DO NOT EDIT!


#ifndef SERVER_MESSAGE_ADDINTSRESPONSE_H
#define SERVER_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server
{
template <class ContainerAllocator>
struct AddintsResponse_
{
  typedef AddintsResponse_<ContainerAllocator> Type;

  AddintsResponse_()
    : sum(0)  {
    }
  AddintsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::server::AddintsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server::AddintsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddintsResponse_

typedef ::server::AddintsResponse_<std::allocator<void> > AddintsResponse;

typedef boost::shared_ptr< ::server::AddintsResponse > AddintsResponsePtr;
typedef boost::shared_ptr< ::server::AddintsResponse const> AddintsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server::AddintsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server::AddintsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server::AddintsResponse_<ContainerAllocator1> & lhs, const ::server::AddintsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server::AddintsResponse_<ContainerAllocator1> & lhs, const ::server::AddintsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server::AddintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server::AddintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AddintsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server::AddintsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AddintsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server::AddintsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server::AddintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::server::AddintsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::server::AddintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server/AddintsResponse";
  }

  static const char* value(const ::server::AddintsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server::AddintsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::server::AddintsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server::AddintsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddintsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server::AddintsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server::AddintsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_MESSAGE_ADDINTSRESPONSE_H
